"""Single funnel for weakly-typed ``meshlib.mrmeshpy`` / ``mrmeshnumpy`` calls.

The MeshLib Python bindings are autogenerated from C++ and have thin type
stubs. To keep the rest of the codebase typed and resilient to upstream
signature drift, every direct call into ``mrmeshpy`` or ``mrmeshnumpy`` flows
through this module. Anywhere else in ``meshlite``, you should import from
``meshlite.domain`` (which re-exports the typed surface) — never from
``meshlib.*`` directly.

Verified against meshlib 3.1.1.211 on 2026-04-12 (M2).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import meshlib.mrmeshnumpy as _mn  # noqa: I100
import meshlib.mrmeshpy as _mrm

if TYPE_CHECKING:
    import numpy as np

# ---------------------------------------------------------------------------
# Type aliases — re-exported so the rest of the package depends on these names
# rather than the raw meshlib classes.
# ---------------------------------------------------------------------------

MrMesh = _mrm.Mesh
"""Alias for the underlying ``meshlib.mrmeshpy.Mesh`` type."""

MrVector3f = _mrm.Vector3f
MrAffineXf3f = _mrm.AffineXf3f
MrBox3f = _mrm.Box3f


# ---------------------------------------------------------------------------
# Construction / I/O
# ---------------------------------------------------------------------------

def make_cube() -> MrMesh:
    """Build a unit cube centered at the origin (8 verts, 12 tris)."""
    return _mrm.makeCube()


def load(path: str) -> MrMesh:
    """Load a mesh from disk. Format inferred from extension.

    Wraps ``mrmeshpy.loadMesh``. Supports STL, OBJ, PLY, OFF, GLB, GLTF, 3MF,
    DXF, and MeshLib's native ``.mrmesh`` format.
    """
    return _mrm.loadMesh(path)


def save(mesh: MrMesh, path: str) -> None:
    """Save a mesh to disk. Format inferred from extension.

    Wraps ``mrmeshpy.saveMesh``. Note the argument order: ``(mesh, path)``.
    """
    _mrm.saveMesh(mesh, path)


# ---------------------------------------------------------------------------
# Cloning
# ---------------------------------------------------------------------------

def clone(mesh: MrMesh) -> MrMesh:
    """Deep copy of a mesh.

    Implemented via ``mrmeshpy.Mesh(other)`` (the C++ copy constructor).
    Verified to be a true deep copy in M2: mutating the clone does not affect
    the original. This is load-bearing for our snapshot-based undo strategy
    (Risks #2 in the plan).
    """
    return _mrm.Mesh(mesh)


# ---------------------------------------------------------------------------
# Topology / counts
# ---------------------------------------------------------------------------

def num_vertices(mesh: MrMesh) -> int:
    """Number of valid (non-deleted) vertices."""
    return mesh.topology.numValidVerts()


def num_faces(mesh: MrMesh) -> int:
    """Number of valid (non-deleted) triangle faces."""
    return mesh.topology.numValidFaces()


def num_holes(mesh: MrMesh) -> int:
    """Number of distinct boundary loops (= holes if you want it watertight)."""
    return mesh.topology.findNumHoles()


def is_watertight(mesh: MrMesh) -> bool:
    """Whether the mesh has zero hole boundaries."""
    return num_holes(mesh) == 0


def find_hole_edges(mesh: MrMesh) -> list:
    """One representative edge per hole boundary loop.

    Used by hole-fill operations (M8). The return type is a meshlib
    ``std_vector_EdgeId``; each element can be passed to ``mrmeshpy.fillHole``.
    """
    return mesh.topology.findHoleRepresentiveEdges()


# ---------------------------------------------------------------------------
# Geometry queries
# ---------------------------------------------------------------------------

def surface_area(mesh: MrMesh) -> float:
    """Total surface area."""
    return float(mesh.area())


def volume(mesh: MrMesh) -> float:
    """Signed volume (well-defined only for closed/watertight meshes)."""
    return float(mesh.volume())


def bounding_box(
    mesh: MrMesh,
) -> tuple[tuple[float, float, float], tuple[float, float, float]]:
    """Axis-aligned bounding box as ``((min_x, min_y, min_z), (max_x, max_y, max_z))``."""
    bb = mesh.computeBoundingBox()
    return (
        (float(bb.min.x), float(bb.min.y), float(bb.min.z)),
        (float(bb.max.x), float(bb.max.y), float(bb.max.z)),
    )


# ---------------------------------------------------------------------------
# Numpy interop (for GPU upload in the render layer, M3)
# ---------------------------------------------------------------------------

def get_numpy_verts(mesh: MrMesh) -> np.ndarray:
    """Return the mesh's vertex positions as a ``(N, 3) float64`` array.

    Wraps ``mrmeshnumpy.getNumpyVerts``. The renderer in M3 will cast this
    down to ``float32`` before uploading to a moderngl VBO.
    """
    return _mn.getNumpyVerts(mesh)


def get_numpy_faces(mesh: MrMesh) -> np.ndarray:
    """Return the mesh's triangle face indices as a ``(M, 3) int32`` array.

    Wraps ``mrmeshnumpy.getNumpyFaces`` (note: it takes ``mesh.topology``,
    not the mesh itself — encapsulated here so callers don't need to know).
    """
    return _mn.getNumpyFaces(mesh.topology)


def get_numpy_vert_normals(mesh: MrMesh) -> np.ndarray:
    """Return per-vertex normals as a ``(N, 3) float64`` array.

    Computes them via ``mrmeshpy.computePerVertNormals`` and converts the
    resulting ``VertCoords`` through ``mrmeshnumpy.toNumpyArray``. The render
    layer will downcast to ``float32`` before uploading.
    """
    coords = _mrm.computePerVertNormals(mesh)
    return _mn.toNumpyArray(coords)


# ---------------------------------------------------------------------------
# Primitives (used by axes.py and tests)
# ---------------------------------------------------------------------------

def connected_components_count(mesh: MrMesh) -> int:
    """Number of connected components.

    Uses ``mrmeshpy.getAllComponents(MeshPart(mesh))``. Each component is a
    set of faces reachable from each other via shared edges.
    """
    mp = _mrm.MeshPart(mesh)
    return len(_mrm.getAllComponents(mp))


def average_edge_length(mesh: MrMesh) -> float:
    """Average edge length across all undirected edges."""
    return float(mesh.averageEdgeLength())


def center_from_bbox(mesh: MrMesh) -> tuple[float, float, float]:
    """Center of the axis-aligned bounding box."""
    c = mesh.findCenterFromBBox()
    return (float(c.x), float(c.y), float(c.z))


def make_arrow(
    base: tuple[float, float, float],
    tip: tuple[float, float, float],
    *,
    thickness: float = 0.02,
    cone_radius: float = 0.05,
    cone_size: float = 0.15,
    quality: int = 24,
) -> MrMesh:
    """Build an arrow mesh from ``base`` to ``tip``.

    Wraps ``mrmeshpy.makeArrow``. Used by ``render/axes.py`` to construct the
    R/G/B X/Y/Z axis indicators without depending on trimesh.
    """
    return _mrm.makeArrow(
        _mrm.Vector3f(*base),
        _mrm.Vector3f(*tip),
        thickness,
        cone_radius,
        cone_size,
        quality,
    )
